pybind11 2024-09-13 (58c382a8)
Code extracted from:

    https://github.com/pybind/pybind11.git

at commit 58c382a8e3d7081364d2f5c62e7f429f0412743b (stable).

Upstream Shortlog
-----------------

Aaron Gokaslan (7):
      6f01c60a Improve Python 3.11 support (#3694)
      45219c6b fix: potential memory leak in pypy (#3774)
      dd617dec fix: missing move in eval.h (#3775)
      251516bc Cleanup casters to release none() to avoid ref counting (#4269)
      305c4711 fix: Revert pfect args make iterator (#4234)
      5b395c9b fix: improve bytes to str decoding error handling (#4294)
      a491af61 bugfix: delete proper ctors in gil.h (#4490)

Chekov2k (1):
      15fde1de Add `PYBIND11_SIMPLE_GIL_MANAGEMENT` option (cmake, C++ define) (#4216)

Chris Ohk (1):
      5327c199 docs: Correct minor typos (#3721)

DWesl (1):
      a4f6627d docs: clarify requirements for including pybind11 (#5326)

Eli Schwartz (1):
      882cb769 add --version option to pybind11-config (#4526)

Eric Cousineau (1):
      93d68dd9 cast: Qualify symbol usage in PYBIND11_TYPE_CASTER (#3758)

Ethan Steinberg (2):
      2de6e398 [v2.10] Revert the addition of the GIL check feature (#4432)
      e414c4bd fix: improve the error reporting for inc_ref GIL failures (#4427)

Henry Schreiner (37):
      8c859e48 fix: minor CMake warning fix for unused variable (#3718)
      80589625 ci: fix PyPy (#3768)
      5c2b53b5 chore: bump changelog for 2.9.2 (#3834)
      914c06fb chore: set to version 2.9.2
      412918d1 feat: add entrypoint for cmake modules dir (#4258)
      a8f21107 docs: update changelog (#4265)
      eaa5f7bd Revert "feat: add entrypoint for cmake modules dir" (#4270)
      0e82c360 fix: add flag for overriding classic Python search values (#4195)
      738a6f83 ci: move to final release of 3.11 (#4286)
      f2ee641e docs: prepare for 2.10.1 release (#4279)
      80dc998e chore: bump versions for 2.10.1
      0bd8896a chore: prepare for 2.10.3 (#4437)
      993eb2b6 chore: update to black 23 (#4482)
      1cae8dc0 fix: tests dir has started to show up in packaging (#4510)
      f5cff4f2 fix: nicer stack level for warning (#4516)
      3f5a7e55 docs: changelog for 2.10.4 (#4532)
      5b0a6fc2 chore: bump version to 3.10.4
      63020d33 docs: prepare for 2.13.1 (#5203)
      941f45bc chore: prepare for 2.13.1
      f50830ea tests: run on pyodide (#4745)
      d8fcfe34 fix(cmake): add required emscripten flags (#5298)
      6d5704cd docs: prepare for 2.13.2 (#5299)
      07f30430 chore: prepare for 2.13.2
      835139f5 fix: emscripten cmake issue (#5301)
      45eaee91 fix: quote paths from pybind11-config (#5302)
      7662af69 docs: prepare for 2.13.3
      bd676436 chore: prepare for 2.13.3
      75c11769 Revert "fix: quote paths from pybind11-config (#5302)" (#5309)
      63b0d146 docs: prepare for 2.13.4 (#5312)
      c6239a8a chore: version 2.13.4
      b0050f30 fix: never use `..` in a header include (#5321)
      0d21cadc fix: allow -Wpedantic in C++20 mode (#5322)
      b3f5f2e7 docs: prepare for 2.13.5 (#5327)
      7c33cdc2 chore: prepare for 2.13.5
      7b67d8e9 docs: update changelog for 2.13.6 (#5372)
      e445ca2b ci: PyPI attestations (#5374)
      a2e59f0e chore: bump to 2.13.6

Lalaland (1):
      ce63bcb9 Fix casts to void* (#4275)

Markus Bauer (1):
      973a16e9 fix: escape paths with spaces in pybind11-config (#4874)

Michael Carlstrom (3):
      dd0e4a0b feat(types): add support for Typing.Callable Special Case (#5202)
      65afa13e fix: add guard for GCC <10.3 on C++20 (#5205)
      a4dd41a1 feat(types) Adds special Case for empty C++ tuple type annotation (#5214)

Mike Essenmacher (1):
      1f4cf8fe Replace "whitelist" with "allowlist" (#4506)

ObeliskGate (2):
      ff3ca786 fix: `<ranges>` support for `py::tuple` and `py::list` (#5314)
      b9f85757 fix: using `__cpp_nontype_template_args` instead of `__cpp_nontype_template_parameter_class` (#5330)

Ralf Gommers (1):
      b4307453 docs: extend `PYBIND11_MODULE` documentation, mention `mod_gil_not_used` (#5250)

Ralf W. Grosse-Kunstleve (16):
      895fc663 ci: update PGI build (old one no longer signed) (#4260)
      3fb36a99 fix: unicode surrogate character in Python exception message. (#4297)
      0abe64c5 Fix `detail::obj_class_name()` to work correctly for meta classes. (#4436)
      050de893 ci: remove clang 10 C++20 (it broke recently) (#4438)
      f14bb03d Add clang15 C++20 job (#4443)
      4f6183cf Ensure `import pybind11_tests` traceback is shown. (#4455)
      5ece09ad Resolve new flake8 error (#4462)
      c0e2eeba Bump isort version to 5.12.0 (#4480)
      c773a02a Appease new flake8 B028 error: (#4513)
      9a1eeed0 Make warning suppressions MINGW-specific again. (#4515)
      2965fa8d Preparation for v2.11.1 patch release (#4752)
      8a099e44 Fix version number mishap: actually update 0 to 1 (#4756)
      129934ad Small cleanup/refactoring in support of PR #5213 (#5251)
      042c3cfd clang-tidy upgrade (to version 18) (#5272)
      570d323b Add `while True` & `top` method to FAQ. (#5340)
      a5fcc560 Enable type-safe interoperability between different independent Python/C++ bindings systems. (#5296)

Sam Gross (3):
      3b47b464 fix: use manual padding of instance_map_shard (#5200)
      8443d084 Use PyMutex instead of std::mutex in free-threaded build. (#5219)
      f3a6d414 fix: make gil_safe_call_once thread-safe in free-threaded CPython (#5246)

StarQTius (1):
      42455b5e fix: clear local internals after finalizing interpreter #2101 (#3744)

Stefano Rivera (1):
      bdec5737 Use sysconfig in Python >= 3.10 (#3764)

Theodore Tsirpanis (1):
      667563dd docs: remove outdated known limitation. (#5263)

Varun Agrawal (1):
      3074608e fix(cmake): remove extra = in flto assignment (#5207)

Vasily Litvinov (1):
      9e6a67d5 Properly translate C++ exception to Python exception when creating Python buffer from wrapped object (#5324)

Vemund Handeland (1):
      1f187d9a Fix char8_t support (#4278)

Xiaofei Wang (1):
      78e26321 Add `type_caster_std_function_specializations` feature. (#4597)

albanD (1):
      da780a00 Make sure to properly untrack gc objects before freeing them (#4461)

cyy (1):
      9d6a79c0 fix: issuses detected by static analyzer (#4440)

dependabot[bot] (9):
      c06f324c chore(deps): bump ilammy/msvc-dev-cmd from 1.12.0 to 1.12.1 (#4493)
      ec3f6e24 chore(deps): bump pypa/gh-action-pypi-publish from 1.6.4 to 1.8.1 (#4576)
      ea10a69d chore(deps): bump actions/attest-build-provenance in the actions group (#5216)
      4b2f7cd6 chore(deps): bump certifi from 2024.2.2 to 2024.7.4 in /docs (#5226)
      d699e99c chore(deps): bump actions/attest-build-provenance in the actions group (#5243)
      fe808a01 chore(deps): bump the actions group with 2 updates (#5287)
      6ee574fa chore(deps): bump actions/attest-build-provenance in the actions group (#5297)
      0a96ff7e chore(deps): bump actions/attest-build-provenance in the actions group (#5335)
      54ab4249 chore(deps): bump the actions group with 2 updates (#5361)

fred-sch (1):
      f9ae715d fix: typo in documentation (#5284)

kajananchinniah (1):
      0ed64a04 docs: fixed typo in spelling of first (#4428)

pre-commit-ci[bot] (5):
      d78de295 chore(deps): update pre-commit hooks (#4439)
      3ea37d04 chore(deps): update pre-commit hooks (#4495)
      41726b64 chore(deps): update pre-commit hooks (#5220)
      44d0d9a4 chore(deps): update pre-commit hooks (#5288)
      36ee4674 chore(deps): update pre-commit hooks (#5350)

pwdcd (1):
      6685547e chore: remove repetitive words (#5308)

wenqing (1):
      639ca6a7 Fixed a compilation error with gcc 14 (#5208)

xkszltl (1):
      b596235f Inconsistent comments between 2 templates of `unchecked()`. (#4519)