Fix Win32 Narrowing Error
Fix
```
2025-01-16T05:51:21.6362891Z D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.10.2\source\adios2\toolkit\format\bp5\BP5Serializer.cpp(1603,68): error C2397: conversion from 'uint64_t' to 'size_t' requires a narrowing conversion [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
2025-01-16T05:51:21.6371102Z D:\a\openPMD-api\openPMD-api\src\dep-adios2\ADIOS2-2.10.2\source\adios2\toolkit\format\bp5\BP5Serializer.cpp(1611,69): error C2397: conversion from 'uint64_t' to 'size_t' requires a narrowing conversion [D:\a\openPMD-api\openPMD-api\src\build-adios2\source\adios2\adios2_core.vcxproj]
```
with MSVC on Win32 ILP32.

`core::iovec` is a `void*` and `size_t`, so this part needs to be `size_t` as well.